export const SET_LODDING = 'AbuseReportV2/SET_LODDING'

export const CREATE_USER_SUCCESS = 'RegistDiverForm/CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'RegistDiverForm/CREATE_USER_FAIL'

export const LOGIN_USER_SUCCESS = 'RegistDiverForm/LOGIN_USER_SUCCESS'

export const FILL_EXTRAUSERINFO_SUCCESS = 'RegistDiverForm/FILL_EXTRAUSERINFO_SUCCESS'
export const FILL_PROINFO_SUCCESS = 'RegistDiverForm/FILL_PROINFO_SUCCESS'
export const CONTINUE_AMB_PROCESS = 'RegistDiverForm/CONTINUE_AMB_PROCESS'
export const FILL_AMBINFO_SUCCESS = 'RegistDiverForm/FILL_AMBINFO_SUCCESS'
export const SUCCESS_APPLY_BUSINESS = 'RegistDiverForm/SUCCESS_APPLY_BUSINESS'
export const SUCCESS_APPLY_RESELLER = 'RegistDiverForm/SUCCESS_APPLY_RESELLER'

export const GENERAL_FAIL = 'RegistDiverForm/GENERAL_FAIL'
export const FINAL_FINISH = 'RegistDiverForm/FINAL_FINISH'
export const EXISTING_RESELLETR_FINAL = 'RegistDiverForm/EXISTING_RESELLETR_FINAL'

export const FILL_EXTRAUSERINFO_SUCCESS_NOAPPLYPRO = 'RegistDiverForm/FILL_EXTRAUSERINFO_SUCCESS_NOAPPLYPRO'
export const RENDER_PRO_FINALPAGE = 'RegistDiverForm/RENDER_PRO_FINALPAGE'
